const userRows = [
    
    {
        id: 1,
        username: "user1",
        fullname: "Nguyen Van A",
        photo: "https://static.productionready.io/images/smiley-cyrus.jpg",
        address: "Ha Noi",
        phone: "0234455555",
    },
    {
        id: 2,
        username: "user2",
        fullname: "Nguyen Van B",
        photo: "https://static.productionready.io/images/smiley-cyrus.jpg",
        address: "Ha Noi",
        phone: "0234455555",
    },
    {   id: 3,
        username: "user3",
        fullname: "Nguyen Van C",
        photo: "https://static.productionready.io/images/smiley-cyrus.jpg",
        address: "Ha Noi",
        phone: "0234455555",
    },
    {   id: 4,
        username: "user4",
        fullname: "Nguyen Van D",
        photo: "https://static.productionready.io/images/smiley-cyrus.jpg",
        address: "Ha Noi",
        phone: "0234455555",
    },
    {   id: 5,
        username: "user5",
        fullname: "Nguyen Van E",
        photo: "https://static.productionready.io/images/smiley-cyrus.jpg",
        address: "Ha Noi",
        phone: "0234455555",
    },



    {
        id: 6,
        username: "user1",
        fullname: "Nguyen Van A",
        photo: "https://static.productionready.io/images/smiley-cyrus.jpg",
        address: "Ha Noi",
        phone: "0234455555",
    },
    {
        id: 7,
        username: "user2",
        fullname: "Nguyen Van B",
        photo: "https://static.productionready.io/images/smiley-cyrus.jpg",
        address: "Ha Noi",
        phone: "0234455555",
    },
    {   id: 8,
        username: "user3",
        fullname: "Nguyen Van C",
        photo: "https://static.productionready.io/images/smiley-cyrus.jpg",
        address: "Ha Noi",
        phone: "0234455555",
    },
    {   id: 9,
        username: "user4",
        fullname: "Nguyen Van D",
        photo: "https://static.productionready.io/images/smiley-cyrus.jpg",
        address: "Ha Noi",
        phone: "0234455555",
    },
    {   id: 10,
        username: "user353",
        fullname: "Nguyen Van E",
        photo: "https://static.productionready.io/images/smiley-cyrus.jpg",
        address: "Ha Noi",
        phone: "0234455555",
    },
]

export {userRows}